### PR TITLE
Add support for specifying tuning parameters for Passenger

### PR DESCRIPTION
**Pull request by djjudas21**
Add support for specifying the following Passenger parameters:
* passenger_max_pool_size
* passenger_high_performance
* passenger_max_requests
* passenger_stat_throttle_rate

### CODE REVIEW

**Comment by djjudas21** [comment]
OK all the tests are now passing for the stuff I added. I'm not sure I understand this one:

```
  1) puppet::repo::puppetlabs on Debian operatingsystems should contain puppetlabs apt repos
     Failure/Error: should contain_apt__source('puppetlabs').with(
     Puppet::Error:
       Invalid parameter key_content on Apt::Source[puppetlabs] at /home/travis/build/stephenrjohnson/puppetmodule/spec/fixtures/modules/puppet/manifests/repo/puppetlabs.pp:13 on node testing-worker-linux-3da96de7-2-3548-linux-12-61590540
```

**Comment by djjudas21** [comment]
Looks like the master also has the same Travis error with `puppet::repo::puppetlabs` so I don't see why this branch shouldn't be merged :)

**Comment by djjudas21** [comment]
Cool, thanks. Any chance you could make an updated release on Puppet Forge?

**Comment by ikalinin** [comment]
I am getting this error now with because if this change:

**Comment by djjudas21** [comment]
Oops. I've sent a patch in #112

**Pull request merged**
